# Generated by Django 3.1.6 on 2021-04-13 07:49

from django.db import migrations, models
import django.db.models.deletion
import runtest.models.version_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValueSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, help_text='This row was created by this User', max_length=30, null=True, verbose_name='Created By')),
                ('created_on', models.DateTimeField(blank=True, editable=False, help_text='Created on this date and time', null=True, verbose_name='Created On')),
                ('updated_by', models.CharField(blank=True, editable=False, help_text='This row was last updated by this User', max_length=30, null=True, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(blank=True, editable=False, help_text='Last updated on this date and time', null=True, verbose_name='Updated On')),
                ('last_version', runtest.models.version_field.VersionField(blank=True, default=0, null=True)),
                ('value_set_code', models.CharField(max_length=30, unique=True, verbose_name='Value Set Code')),
                ('value_set_description', models.CharField(blank=True, help_text='A helpful description of this Value Set', max_length=60, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'value_set',
            },
        ),
        migrations.CreateModel(
            name='ValueSetMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, editable=False, help_text='This row was created by this User', max_length=30, null=True, verbose_name='Created By')),
                ('created_on', models.DateTimeField(blank=True, editable=False, help_text='Created on this date and time', null=True, verbose_name='Created On')),
                ('updated_by', models.CharField(blank=True, editable=False, help_text='This row was last updated by this User', max_length=30, null=True, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(blank=True, editable=False, help_text='Last updated on this date and time', null=True, verbose_name='Updated On')),
                ('last_version', runtest.models.version_field.VersionField(blank=True, default=0, null=True)),
                ('value_code', models.CharField(help_text='A Unique Value Code within this Value Set', max_length=30, verbose_name='Value Code')),
                ('value_description', models.CharField(blank=True, help_text='A helpful description of this Value Code', max_length=60, null=True, verbose_name='Description')),
                ('sort_order', models.PositiveSmallIntegerField(blank=True, help_text='Optionally override sorting by Value Code', null=True, verbose_name='Sort Order')),
                ('param_1', models.CharField(blank=True, help_text='Optional Parameter 1', max_length=30, null=True, verbose_name='Parameter 1')),
                ('param_2', models.CharField(blank=True, help_text='Optional Parameter 2', max_length=30, null=True, verbose_name='Parameter 2')),
                ('param_3', models.CharField(blank=True, help_text='Optional Parameter 3', max_length=30, null=True, verbose_name='Parameter 3')),
                ('value_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runtest.valueset', verbose_name='Value Set')),
            ],
            options={
                'db_table': 'value_set_member',
            },
        ),
    ]
