# Generated by Django 3.1.6 on 2021-04-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valueset',
            name='created_by',
            field=models.CharField(blank=True, editable=False, help_text='This row was created by this User', max_length=150, null=True, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, help_text='This row was last updated by this User', max_length=150, null=True, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='valuesetmember',
            name='created_by',
            field=models.CharField(blank=True, editable=False, help_text='This row was created by this User', max_length=150, null=True, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='valuesetmember',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, help_text='This row was last updated by this User', max_length=150, null=True, verbose_name='Updated By'),
        ),
    ]
