# Generated by Django 3.2 on 2021-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtest', '0003_auto_20210421_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='step_by',
            field=models.IntegerField(null=True, verbose_name='Increment By'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='indicator_1_code',
            field=models.CharField(blank=True, choices=[], help_text='Indicator 1 used for this backtest run', max_length=30, null=True, verbose_name='Indicator 1'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='indicator_2_code',
            field=models.CharField(blank=True, choices=[], help_text='Indicator 2 used for this backtest run', max_length=30, null=True, verbose_name='Indicator 2'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='indicator_3_code',
            field=models.CharField(blank=True, choices=[], help_text='Indicator 3 used for this backtest run', max_length=30, null=True, verbose_name='Indicator 3'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='stock_ticker',
            field=models.CharField(choices=[], help_text='Stock to be selected for this backtest run', max_length=200, verbose_name='Stock Ticker'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='strategy_code',
            field=models.CharField(choices=[], help_text='Strategy to use when triggering trades using Indicators', max_length=30, verbose_name='Strategy'),
        ),
    ]
