# Generated by Django 3.2 on 2021-05-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtest', '0004_auto_20210426_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='trade_size',
            field=models.IntegerField(help_text='Number of contracts to trade', null=True, verbose_name='Contract Size'),
        ),
    ]
