# Generated by Django 3.2 on 2021-05-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtest', '0005_alter_testrun_trade_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='historySet',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock_ticker', models.CharField(max_length=4)),
                ('test_parameter', models.CharField(max_length=64)),
                ('percent_winning_trade', models.FloatField()),
                ('average_win', models.FloatField()),
                ('remark', models.CharField(max_length=512)),
            ],
        ),
    ]
