# Generated by Django 3.2 on 2021-05-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtest', '0006_historyset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='historySet',
        ),
    ]
