# Generated by Django 3.2 on 2021-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtest', '0007_delete_historyset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='portfolio_end',
            field=models.IntegerField(help_text='Final Capital Amount when Backtest Ends', null=True, verbose_name='Final Capital'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='portfolio_start',
            field=models.IntegerField(help_text='Backtest will start with this initial capital amount', verbose_name='Initial Capital'),
        ),
    ]
