# Generated by Django 3.2 on 2021-09-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtest', '0009_alter_testrun_portfolio_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='portfolio_start',
            field=models.IntegerField(default=100000, help_text='Backtest will start with this starting capital amount', verbose_name='Starting Capital'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='stock_ticker',
            field=models.CharField(choices=[], help_text='Stock to be selected for this backtest run', max_length=200, verbose_name='Stock Name'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='trade_size',
            field=models.IntegerField(default=1000, help_text='', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='stock_ticker',
            field=models.CharField(max_length=30, verbose_name='Stock Ticker'),
        ),
    ]
