# Generated by Django 3.2 on 2021-09-29 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runtest', '0010_auto_20210922_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuesetmember',
            name='param_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='param_4', to='runtest.parameter', verbose_name='Parameter 4'),
        ),
        migrations.AddField(
            model_name='valuesetmember',
            name='param_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='param_5', to='runtest.parameter', verbose_name='Parameter 5'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='trade_size',
            field=models.IntegerField(default=1000, help_text='', null=True, verbose_name=''),
        ),
    ]
