# Generated by Django 3.2 on 2021-09-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtest', '0011_auto_20210929_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='drawdown_date',
            field=models.DateField(null=True, verbose_name='Drawdown Date'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='equity_performance',
            field=models.FloatField(null=True, verbose_name='Equity Performance'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='equity_roi',
            field=models.FloatField(null=True, verbose_name='Equity ROI'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='ind_1_param_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Param 4'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='ind_1_param_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Param 5'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='ind_2_param_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Param 4'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='ind_2_param_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Param 5'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='ind_3_param_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Param 4'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='ind_3_param_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Param 5'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='max_drawdown',
            field=models.FloatField(null=True, verbose_name='Maximum Drawdown'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='trades',
            field=models.PositiveIntegerField(help_text='Number of trades made', null=True, verbose_name='Trades'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='win_rate',
            field=models.FloatField(null=True, verbose_name='Win Rate'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='portfolio_end',
            field=models.IntegerField(help_text='Final Capital Amount when Backtest Ends', null=True, verbose_name='Final Equity'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='portfolio_start',
            field=models.IntegerField(default=10000, help_text='Backtest will start with this initial capital amount', verbose_name='Initial Capital'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='trade_size',
            field=models.IntegerField(default=1000, help_text='Units per trade', null=True, verbose_name='Trade Size'),
        ),
    ]
