# Generated by Django 3.2 on 2021-09-30 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('runtest', '0012_auto_20210929_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='indicator_1_code',
            field=models.CharField(blank=True, help_text='Indicator 1 used for this backtest run', max_length=30, null=True, verbose_name='Indicator 1'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='indicator_2_code',
            field=models.CharField(blank=True, help_text='Indicator 2 used for this backtest run', max_length=30, null=True, verbose_name='Indicator 2'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='indicator_3_code',
            field=models.CharField(blank=True, help_text='Indicator 3 used for this backtest run', max_length=30, null=True, verbose_name='Indicator 3'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='run_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='stock_ticker',
            field=models.CharField(help_text='Stock to be selected for this backtest run', max_length=200, verbose_name='Stock Name'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='strategy_code',
            field=models.CharField(help_text='Strategy to use when triggering trades using Indicators', max_length=30, verbose_name='Strategy'),
        ),
    ]
