# Generated by Django 3.2 on 2021-11-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtest', '0014_testrun_indicators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='ind_2_param_1',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='ind_2_param_2',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='ind_2_param_3',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='ind_2_param_4',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='ind_2_param_5',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='ind_3_param_1',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='ind_3_param_2',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='ind_3_param_3',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='ind_3_param_4',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='ind_3_param_5',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='indicator_2_code',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='indicator_3_code',
        ),
        migrations.AlterField(
            model_name='testrun',
            name='indicator_1_code',
            field=models.CharField(blank=True, help_text='Indicator used for this backtest run', max_length=30, null=True, verbose_name='Indicator'),
        ),
    ]
