apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-container
  template:
    metadata:
      labels:
        app: nginx-container
    spec:
      containers:
        - name: nginx-container
          imagePullPolicy: IfNotPresent
          image: backtest_nginx
          ports:
          - containerPort: 8080

