kind: Service
apiVersion: v1
metadata:
  # Match our docker-compose host name
  name: nginx
spec:
  selector:
    app: nginx-container
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
