kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbdata-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: dbdata-pv
