kind: Service
apiVersion: v1
metadata:
  # Match our docker-compose host names
  name: web
spec:
  selector:
    app: web-container
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
