apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backtest-ingress
spec:
  rules:
  - host: thecube.atsc.org.my
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 8080
